#!/usr/bin/env python3
"""Turn the captured cabinet impulse responses into Source/dsp/CabinetIr.h.

The plug-in ships four measurements taken from Jester's Brutal Pack 1.0 by Bastian
Karschewski (Jester Dyne Productions), released under CC0 1.0 - public domain, so they
can be redistributed inside a GPL binary without adding any obligation of their own.

    https://www.jester-dyne-productions.com/brutal-ir-pack/

Two captures per cabinet, same speaker, different microphone, blended per voicing. They
must stay sample-aligned: all fifteen files in the pack share the same capture timing, so
a straight blend of any two is phase-coherent (measured worst case 0.7 dB of cancellation
at 5 kHz, everywhere else below 0.2 dB).

These are guitar 4x12 captures, and this is a bass plug-in. Nothing below about 80 Hz
survives a cabinet like that, so CabSim adds a modelled ported low end around the
convolution rather than pretending the measurement holds one - see CabSim.h.

Each response is truncated, faded and normalised to one common band level so that
neither the Mic control nor the Cabinet selector produces a jump in loudness. That
level is the average of the four generated FIRs this replaced, so a session saved with
an earlier version comes back at the same volume.

Usage:
    tools/make_cabinet_ir.py <Jesters_Brutal_Pack_1.0/Impulses/48kHz> [-o <header>]
"""

import argparse
import math
import pathlib
import struct
import sys
import wave

# The response is kept long enough that truncation stays under about 1 dB across the
# guitar band; going further mostly buys resolution below 60 Hz, which the speaker
# model high-passes away anyway. See the comment in CabSim.h for the runtime cost.
LENGTH = 1024
FADE = 128

# 150 Hz .. 5 kHz, the band a guitar cabinet is actually judged on. Narrow enough to
# ignore the sub roll-off, wide enough that a single deep notch cannot move the result.
BAND_LOW, BAND_HIGH, BAND_POINTS = 150.0, 5000.0, 25

# Average band level of the four FIRs generated by the previous CabSim (vintage
# edge/centre 0.767/3.649 dB, modern edge/centre 4.391/6.204 dB).
TARGET_BAND_DB = 3.7528

SOURCE_RATE = 48000

# Speakers and microphones are from the pack's handbook. Edge is the darker capture of
# the pair and sits at Mic = 0; centre is the brighter one at Mic = 100.
CABINETS = [
    ("vintage", "Celestion Vintage 30",
     ("edge",   "1_Cookie_Monster.wav",      "SM57"),
     ("centre", "9_Devils_Cunnilingus.wav",  "PDMIC75")),
    ("modern",  "Eminence DV-77",
     ("edge",   "2_Darth_Genocider.wav",     "SM57"),
     ("centre", "10_October_32th.wav",       "SM57, further off-axis")),
]


def read_wav(path):
    """Mono PCM only - the pack is 24-bit, but 16 and 32-bit are accepted as well."""
    with wave.open(str(path)) as w:
        if w.getnchannels() != 1:
            sys.exit(f"{path.name}: expected mono, got {w.getnchannels()} channels")
        if w.getframerate() != SOURCE_RATE:
            sys.exit(f"{path.name}: expected {SOURCE_RATE} Hz, got {w.getframerate()} Hz")

        width = w.getsampwidth()
        raw = w.readframes(w.getnframes())

    if width == 3:
        samples = []
        for i in range(0, len(raw), 3):
            v = raw[i] | (raw[i + 1] << 8) | (raw[i + 2] << 16)
            samples.append((v - 0x1000000 if v & 0x800000 else v) / 8388608.0)
        return samples

    if width == 2:
        return [v / 32768.0 for v in struct.unpack(f"<{len(raw) // 2}h", raw)]

    if width == 4:
        return [v / 2147483648.0 for v in struct.unpack(f"<{len(raw) // 4}i", raw)]

    sys.exit(f"{path.name}: unsupported sample width {width * 8} bit")


def band_level_db(ir):
    """Average magnitude in dB over the judging band. The runtime repeats this after
    resampling, so both ends of the pipeline agree on what 'the same loudness' means."""
    total = 0.0

    for i in range(BAND_POINTS):
        f = BAND_LOW * (BAND_HIGH / BAND_LOW) ** (i / (BAND_POINTS - 1))
        re = im = 0.0

        for n, v in enumerate(ir):
            phase = 2.0 * math.pi * f * n / SOURCE_RATE
            re += v * math.cos(phase)
            im -= v * math.sin(phase)

        total += 20.0 * math.log10(math.sqrt(re * re + im * im) + 1e-12)

    return total / BAND_POINTS


def prepare(samples):
    ir = list(samples[:LENGTH]) + [0.0] * max(0, LENGTH - len(samples))

    # A cosine fade over the tail: cutting a decaying capture off mid-cycle puts a step
    # into the response and rings across the whole spectrum.
    for n in range(LENGTH - FADE, LENGTH):
        p = (n - (LENGTH - FADE)) / (FADE - 1)
        ir[n] *= 0.5 + 0.5 * math.cos(math.pi * p)

    scale = 10.0 ** ((TARGET_BAND_DB - band_level_db(ir)) / 20.0)
    return [v * scale for v in ir]


def emit(f, name, ir, description):
    f.write(f"/** {description} */\n")
    f.write(f"inline constexpr float {name}[kLength] =\n{{\n")

    for start in range(0, LENGTH, 6):
        row = ", ".join(f"{v: .8e}f" for v in ir[start:start + 6])
        f.write(f"    {row},\n")

    f.write("};\n\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("impulses", type=pathlib.Path,
                        help="the pack's Impulses/48kHz directory")
    parser.add_argument("-o", "--output", type=pathlib.Path,
                        default=pathlib.Path(__file__).resolve().parent.parent
                                / "Source" / "dsp" / "CabinetIr.h")
    args = parser.parse_args()

    responses = []

    for cabinet, speaker, *positions in CABINETS:
        for position, filename, mic in positions:
            path = args.impulses / filename
            if not path.is_file():
                sys.exit(f"missing {path}")

            ir = prepare(read_wav(path))
            responses.append((f"{cabinet}{position.capitalize()}", ir,
                              f"{speaker}, {mic}. From {filename}."))
            print(f"  {cabinet:8s} {position:6s}  {filename:24s} "
                  f"{speaker}, {mic}  ->  {band_level_db(ir):+.3f} dB")

    args.output.parent.mkdir(parents=True, exist_ok=True)

    with args.output.open("w") as f:
        f.write(f"""/*
    The Collapse of The Wave Function - bass drive, blend and cabinet
    Copyright (C) 2026 doctorspider42

    This program is free software: you can redistribute it and/or modify it under the
    terms of the GNU General Public License as published by the Free Software
    Foundation, either version 3 of the License, or (at your option) any later version.

    It links against JUCE 8 under the AGPLv3, so every distributed binary additionally
    carries AGPLv3 section 13. See LICENSE and LICENSE.AGPLv3.

    This program is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
    PARTICULAR PURPOSE. See the GNU General Public License for more details.

    ---------------------------------------------------------------------------
    GENERATED FILE - do not edit. Regenerate with:

        tools/make_cabinet_ir.py <Jesters_Brutal_Pack_1.0/Impulses/48kHz>

    The measurements themselves are from Jester's Brutal Pack 1.0 by Bastian
    Karschewski (Jester Dyne Productions), dedicated to the public domain under
    CC0 1.0: https://www.jester-dyne-productions.com/brutal-ir-pack/
    Cabinet: a modified oversized Behringer BG412S 4x12.
    ---------------------------------------------------------------------------
*/

#pragma once

namespace collapse::dsp::ir
{{

inline constexpr double kSourceSampleRate = {SOURCE_RATE}.0;
inline constexpr int    kLength           = {LENGTH};

/** Every response is normalised to this average level over {BAND_LOW:.0f} Hz .. {BAND_HIGH / 1000.0:.0f} kHz, so
    switching cabinet never changes loudness. CabSim measures the same figure after
    resampling, corrects for it, and then trims the whole response to unity in band. */
inline constexpr double kBandLevelDb   = {TARGET_BAND_DB};
inline constexpr double kBandLowHz     = {BAND_LOW};
inline constexpr double kBandHighHz    = {BAND_HIGH};
inline constexpr int    kBandPoints    = {BAND_POINTS};

""")

        for name, ir, description in responses:
            emit(f, name, ir, description)

        f.write("} // namespace collapse::dsp::ir\n")

    print(f"wrote {args.output} ({args.output.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
